[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "graph-wrap"
dynamic = ["version"]
description = "A wrapper for LangGraph agents that handles observability and guardrails"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langgraph",
    "langgraph-checkpoint-postgres",
    "psycopg[binary]"
]

[project.optional-dependencies]
ui = [
    "streamlit"
]

[project.scripts]
graph-wrap-ui = "graph_wrap.cli:main"


[tool.hatch.version]
path = "src/graph_wrap/__init__.py"
